info:
  app:
    name: "Continuous Delivery"
    version: "1.0.0"
    description: "Example repo for showcasing best practices around Continuous Delivery"

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  liquibase:
    change-log: "classpath:liquibase/master.xml"
