info:
  app:
    name: "Continuous Delivery"
    version: "1.0.0"
    description: "Example repo for showcasing best practices around Continuous Delivery"

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://[::1]:5432/continuous_delivery
    username: admin
    password: password
