info:
  app:
    name: "Continuous Delivery"
    version: "1.0.0"
    description: "Example repo for showcasing best practices around Continuous Delivery"

spring:
  thymeleaf:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://0.0.0.0:5432/continuous_delivery
    username: admin
    password: password
---
spring:
  profiles: docker-compose
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://postgres:5432/continuous_delivery
    username: admin
    password: password

