version: '3'

networks:
  shared-network:
    driver: bridge

services:
  database:
    image: "postgres:11-alpine"
    container_name: postgres
    networks:
      - shared-network
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
  app:
    image: "continuous-delivery:0.0.1"
    container_name: continuous-delivery
    networks:
      - shared-network
    ports:
    - "8080:8080"
    command: ["java", "-jar", "continuous-delivery-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=docker-compose"]
    depends_on:
      - database